// <auto-generated />
using System;
using LibraryApplication.Infastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LibraryApplication.Infastructure.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LibraryApplication.Domain.AggregateModel.EmployeesAggregate.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCEO")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManager")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<double>("Salary")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("LibraryApplication.Domain.AggregateModel.LibrayAggregate.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LibraryApplication.Domain.LibraryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Borrower")
                        .HasColumnType("text");

                    b.Property<bool>("IsBorrowable")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("categoryId")
                        .HasColumnName("CategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("categoryId");

                    b.ToTable("LibraryItems");

                    b.HasDiscriminator<string>("Type").HasValue("LibraryItem");
                });

            modelBuilder.Entity("LibraryApplication.Domain.AggregateModel.LibrayAggregate.AudioBook", b =>
                {
                    b.HasBaseType("LibraryApplication.Domain.LibraryItem");

                    b.Property<int>("RunTimeMinutes")
                        .HasColumnName("RunTimeMinutes")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("AudioBook");
                });

            modelBuilder.Entity("LibraryApplication.Domain.AggregateModel.LibrayAggregate.Book", b =>
                {
                    b.HasBaseType("LibraryApplication.Domain.LibraryItem");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnName("Author")
                        .HasColumnType("text");

                    b.Property<int>("Pages")
                        .HasColumnName("Pages")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Book");
                });

            modelBuilder.Entity("LibraryApplication.Domain.AggregateModel.LibrayAggregate.Dvd", b =>
                {
                    b.HasBaseType("LibraryApplication.Domain.LibraryItem");

                    b.Property<int>("RunTimeMinutes")
                        .HasColumnName("RunTimeMinutes")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Dvd");
                });

            modelBuilder.Entity("LibraryApplication.Domain.AggregateModel.LibrayAggregate.ReferenceBook", b =>
                {
                    b.HasBaseType("LibraryApplication.Domain.LibraryItem");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnName("Author")
                        .HasColumnType("text");

                    b.Property<int>("Pages")
                        .HasColumnName("Pages")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("ReferenceBook");
                });

            modelBuilder.Entity("LibraryApplication.Domain.LibraryItem", b =>
                {
                    b.HasOne("LibraryApplication.Domain.AggregateModel.LibrayAggregate.Category", "Category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
